# Generated by Django 4.2.5 on 2023-10-11 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_onboard', '0020_alter_softwarecost_amount_ownerequity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('payee', models.CharField(max_length=45)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_date', models.DateTimeField(blank=True, null=True)),
                ('recurring_amount', models.FloatField(blank=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('expense_line_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('unit_discount', models.FloatField()),
                ('total_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('expense_id', models.ForeignKey(db_column='expense_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_items', to='expenses.expense')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='user_onboard.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('attachment_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=255)),
                ('expense_id', models.ForeignKey(db_column='expense_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='expenses.expense')),
            ],
        ),
    ]
