# Generated by Django 4.2.5 on 2023-10-22 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_onboard', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselineitem',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='user_onboard.product'),
        ),
        migrations.AddField(
            model_name='expenseattachment',
            name='expense_id',
            field=models.ForeignKey(db_column='expense_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
