# Generated by Django 4.2.5 on 2023-10-11 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_table_alter_expenseattachment_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselineitem',
            name='expense_line_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
