# Generated by Django 4.2.5 on 2023-10-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='do/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense_id', models.ForeignKey(db_column='expense_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='do_forms', to='expenses.expense')),
            ],
        ),
    ]
