# Generated by Django 4.2.5 on 2023-09-29 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('amount', models.FloatField()),
                ('parent_acc', models.ForeignKey(blank=True, db_column='parent_acc_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.account')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=45)),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='report.account')),
            ],
            options={
                'db_table': 'journal',
            },
        ),
        migrations.CreateModel(
            name='TransactionAction',
            fields=[
                ('action_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sales_title', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.BooleanField()),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='report.account')),
            ],
            options={
                'db_table': 'transaction_action',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledger_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_amount', models.FloatField()),
                ('credit_amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='report.account')),
                ('journal', models.ForeignKey(db_column='journal_id', on_delete=django.db.models.deletion.DO_NOTHING, to='report.journal')),
            ],
            options={
                'db_table': 'ledger',
            },
        ),
    ]
