# Generated by Django 4.2.5 on 2023-10-25 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='AccountUserRelationship',
            fields=[
                ('relationship_id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=45)),
                ('debit_amount', models.FloatField(null=True)),
                ('credit_amount', models.FloatField(null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'journal',
            },
        ),
        migrations.CreateModel(
            name='TransactionAction',
            fields=[
                ('action_id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
                ('sales_title', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_title', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('datafield', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.BooleanField()),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='report.account')),
            ],
            options={
                'db_table': 'transaction_action',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledger_id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('debit_amount', models.FloatField(null=True)),
                ('credit_amount', models.FloatField(null=True)),
                ('balance', models.FloatField()),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.DO_NOTHING, to='report.account')),
                ('journal', models.ForeignKey(db_column='journal_id', on_delete=django.db.models.deletion.DO_NOTHING, to='report.journal')),
            ],
            options={
                'db_table': 'ledger',
            },
        ),
    ]
