# Generated by Django 4.2.5 on 2023-10-19 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AlterField(
            model_name='transactionaction',
            name='action_id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AccountUserRelationship',
            fields=[
                ('relationship_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(blank=True, db_column='acount_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.account')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
    ]
