# Generated by Django 4.2.5 on 2023-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_account_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accountuserrelationship',
            name='relationship_id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
