# Generated by Django 4.2.5 on 2023-10-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='amount',
        ),
        migrations.AddField(
            model_name='accountuserrelationship',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
