# Generated by Django 4.2.5 on 2023-10-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_remove_account_amount_accountuserrelationship_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionaction',
            name='payment',
        ),
    ]
