# Generated by Django 4.2.5 on 2023-10-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_transactionaction_datafield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionaction',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
