# Generated by Django 4.2.5 on 2023-10-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_journal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
