# Generated by Django 4.2.5 on 2023-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_alter_journal_journal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='credit_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='debit_amount',
            field=models.FloatField(null=True),
        ),
    ]
