# Generated by Django 4.2.5 on 2023-10-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20231020_2048'),
        ('report', '0017_auto_20231022_0837'),
    ]

    operations = [
    ]
