# Generated by Django 4.2.5 on 2023-10-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_auto_20231022_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
