# Generated by Django 4.2.5 on 2023-10-26 17:10

from django.db import migrations
from report.models import Account

def seed_data(apps, schema_editor):
    revenue = Account.objects.filter(name="Revenue").first()

    shipping = Account.objects.create(
        name="Shipping Revenue",
        type="revenue",
        parent_acc=revenue
    )

class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_merge_0011_auto_20231020_2048_0017_auto_20231022_0837'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
