# Generated by Django 4.2.5 on 2023-10-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_journal_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='ledger_id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
