# Generated by Django 4.2.5 on 2023-10-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_alter_ledger_ledger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='credit_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='debit_amount',
            field=models.FloatField(null=True),
        ),
    ]
