# Generated by Django 4.2.5 on 2023-10-26 17:43

from django.db import migrations
from report.models import Account, TransactionAction

def seed_data(apps, schema_editor):
    #Main accounts
    expenses = Account.objects.filter(name="Expenses").first()
    account_payable = Account.objects.filter(name="Account Payable").first()

    #Child accounts
    tiktok = Account.objects.create(
        name="TikTok",
        type="expenses",
        parent_acc=expenses
    )

    shoppe = Account.objects.create(
        name="Shopee",
        type="expenses",
        parent_acc=expenses
    )

    #Actions
    TransactionAction.objects.create(
        name="Marketing Expenses",
        expense_title="Marketing - TikTok",
        payment="Credit",
        model="ExpenseLineItem",
        datafield="total_price",
        account=tiktok,
        operation=1
    )
    TransactionAction.objects.create(
        name="Marketing Expenses",
        expense_title="Marketing - TikTok",
        payment="Credit",
        model="Product",
        datafield="cost",
        account=account_payable,
        operation=0
    )

    TransactionAction.objects.create(
        name="Marketing Expenses",
        expense_title="Marketing - Shopee",
        payment="Credit",
        model="ExpenseLineItem",
        datafield="total_price",
        account=shoppe,
        operation=1
    )
    TransactionAction.objects.create(
        name="Marketing Expenses",
        expense_title="Marketing - Shopee",
        payment="Credit",
        model="Product",
        datafield="cost",
        account=account_payable,
        operation=0
    )

class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_auto_20231026_1710'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
