# Generated by Django 4.2.5 on 2023-10-27 17:20

from django.db import migrations
from report.models import Account, TransactionAction

def seed_data(apps, schema_editor):
    expenses = Account.objects.filter(name="Expenses").first()
    cash_account = Account.objects.filter(name="Cash Account").first()

    staff_payroll = Account.objects.create(
        name="Staff Payroll",
        type="expenses",
        parent_acc=expenses
    )

    TransactionAction.objects.create(
        name="Payroll Expenses",
        expense_title="Payroll Expenses",
        payment="Credit",
        model="ExpenseLineItem",
        datafield="total_price",
        account=staff_payroll,
        operation=1
    )

    TransactionAction.objects.create(
        name="Payroll Expenses",
        expense_title="Payroll Expenses",
        payment="Credit",
        model="ExpenseLineItem",
        datafield="total_price",
        account=cash_account,
        operation=0
    )
    

class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_auto_20231026_1743'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
