# Generated by Django 4.2.5 on 2023-10-29 06:52

from django.db import migrations
from report.models import TransactionAction

class Migration(migrations.Migration):

    def seed_data(apps, schema_editor):
        TransactionAction.objects.create(
            name="Sales Revenue (BizApp)",
            sales_title="BizApp Sales- with Inventory",
            payment="Cash",
            model="Inventory",
            operation=0
        )
        TransactionAction.objects.create(
            name="Sales Revenue (BizApp)",
            sales_title="BizApp Sales- with Inventory",
            payment="Credit",
            model="Inventory",
            operation=0
        )
        TransactionAction.objects.create(
            name="Sales Revenue (POS BizApp)",
            sales_title="BizApp POS -with Inventory",
            payment="Cash",
            model="Inventory",
            operation=0
        )
        TransactionAction.objects.create(
            name="Sales Revenue (Self Defined)",
            sales_title="Direct Sales with Inventory",
            payment="Cash",
            model="Inventory",
            operation=0
        )
        TransactionAction.objects.create(
            name="Sales Revenue (Self Defined)",
            sales_title="Direct Sales with Inventory",
            payment="Credit",
            model="Inventory",
            operation=0
        )

    dependencies = [
        ('report', '0022_auto_20231027_1939'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]