# Generated by Django 4.2.5 on 2023-11-01 16:36

from django.db import migrations
from report.models import Account, TransactionAction

class Migration(migrations.Migration):

    def seed_data(apps, schema_editor):

        assets = Account.objects.get(name="Assets")
        fixed_assets = Account.objects.get(name="Fixed Assets")
        liabilities = Account.objects.get(name="Liabilities")
        equity = Account.objects.get(name="Equity")
        
        raw_materials = Account.objects.create(
            name="Raw Materials",
            type="assets",
            parent_acc=assets
        )

        machine_and_equipment = Account.objects.create(
            name="Machine and Equipment",
            type="fixed assets",
            parent_acc=fixed_assets
        )

        investments = Account.objects.create(
            name="Investments",
            type="fixed assets",
            parent_acc=fixed_assets
        )

        accumulated_depreciation = Account.objects.create(
            name="Accumulated Depreciation",
            type="fixed assets",
            parent_acc=fixed_assets
        )

        short_term_debt = Account.objects.create(
            name="Short Term Debt",
            type="liabilities",
            parent_acc=liabilities
        )

        long_term_debt = Account.objects.create(
            name="Long Term Debt",
            type="liabilities",
            parent_acc=liabilities
        )

        owners_capital = Account.objects.create(
            name="Owners Capital",
            type="equity",
            parent_acc=equity
        )

        retained_earnings = Account.objects.create(
            name="Retained Earnings",
            type="equity",
            parent_acc=equity
        )


    dependencies = [
        ('report', '0023_auto_20231029_0652'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
