# Generated by Django 4.2.5 on 2023-11-10 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_do'),
        ('sales', '0004_stakeholder_alter_sales_customer_id_delete_customer'),
        ('report', '0024_auto_20231101_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='expense_id',
            field=models.ForeignKey(db_column='expense_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='journal',
            name='sales_id',
            field=models.ForeignKey(db_column='sales_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sales'),
        ),
        migrations.AddField(
            model_name='journal',
            name='type',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
