# Generated by Django 4.2.5 on 2023-10-29 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionaction',
            name='account',
            field=models.ForeignKey(db_column='account_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.account'),
        ),
    ]
