# Generated by Django 4.2.5 on 2023-11-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='user_id',
            new_name='user',
        ),
    ]
