# Generated by Django 4.2.5 on 2023-09-26 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0005_alter_user_managers_remove_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
