# Generated by Django 4.2.5 on 2023-09-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0009_office'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='office',
            table='office',
        ),
    ]
