# Generated by Django 4.2.5 on 2023-09-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0010_alter_office_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
