# Generated by Django 4.2.5 on 2023-09-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0011_delete_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rent', models.BooleanField()),
                ('electric', models.IntegerField()),
                ('water', models.IntegerField()),
                ('internet', models.IntegerField()),
                ('rental', models.IntegerField()),
                ('rental_deposit', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_onboard.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'office',
            },
        ),
    ]
