# Generated by Django 4.2.5 on 2023-09-26 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0012_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ic_passport', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField()),
                ('position', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('epf', models.FloatField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_onboard.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
