# Generated by Django 4.2.5 on 2023-09-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0015_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
