# Generated by Django 4.2.5 on 2023-09-27 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0016_alter_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('creditor', models.CharField(max_length=255)),
                ('creditor_phone_no', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('amount_payable', models.FloatField()),
                ('interest', models.FloatField()),
                ('installment_amount', models.FloatField()),
                ('not_defined', models.BooleanField()),
                ('recurring', models.BooleanField()),
                ('active', models.BooleanField()),
                ('creditor_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_onboard.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan',
            },
        ),
    ]
