# Generated by Django 4.2.5 on 2023-09-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0017_loans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loans',
            new_name='Loan',
        ),
    ]
