# Generated by Django 4.2.5 on 2023-09-27 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0019_softwarecost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarecost',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='OwnerEquity',
            fields=[
                ('software_cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ic_passport', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('bumiputera', models.BooleanField()),
                ('percentage_ownership', models.FloatField()),
                ('paid_up_capital', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner_equity',
            },
        ),
    ]
