# Generated by Django 4.2.5 on 2023-10-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
                ('price_per_unit', models.FloatField()),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('inventory_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, null=True)),
                ('current_stock', models.FloatField(default=0)),
                ('increase', models.BooleanField()),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
            options={
                'db_table': 'inventory_history',
            },
        ),
    ]
