# Generated by Django 4.2.5 on 2023-10-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryhistory',
            old_name='increse',
            new_name='increase',
        ),
        migrations.AddField(
            model_name='inventoryhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
