# Generated by Django 4.2.5 on 2023-10-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_increse_inventoryhistory_increase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhistory',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
