# Generated by Django 4.2.5 on 2023-09-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFooter',
            fields=[
                ('sales_footer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('terms_and_condition', models.TextField()),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sales_footer',
            },
        ),
        migrations.CreateModel(
            name='SalesLineItems',
            fields=[
                ('sales_line_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=255, unique=True)),
                ('quantity', models.IntegerField()),
                ('unit_discount', models.FloatField()),
                ('total_price', models.FloatField()),
            ],
            options={
                'db_table': 'sales_line_items',
            },
        ),
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('shipping_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tracking_no', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('pricing', models.FloatField()),
            ],
            options={
                'db_table': 'shipping_information',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('bizapp_transaction_no', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('recurring', models.BooleanField(blank=True, null=True)),
                ('recurring_date', models.DateTimeField(blank=True, null=True)),
                ('sales_footer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.salesfooter')),
                ('sales_line_no', models.ForeignKey(db_column='sales_line_no', on_delete=django.db.models.deletion.DO_NOTHING, to='sales.saleslineitems')),
                ('shipping_no', models.ForeignKey(db_column='shipping_no', on_delete=django.db.models.deletion.DO_NOTHING, to='sales.shippinginformation')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
