# Generated by Django 4.2.5 on 2023-10-25 08:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('handphone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('tax_information', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('tiktok', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('bizapp_transaction_no', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_date', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='SalesFooter',
            fields=[
                ('sales_footer_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('terms_and_condition', models.TextField()),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sales_footer',
            },
        ),
        migrations.CreateModel(
            name='SalesLineItems',
            fields=[
                ('sales_line_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_discount', models.FloatField()),
                ('total_price', models.FloatField()),
            ],
            options={
                'db_table': 'sales_line_items',
            },
        ),
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('shipping_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tracking_no', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('pricing', models.FloatField()),
                ('sales_id', models.ForeignKey(db_column='sales_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sales')),
            ],
            options={
                'db_table': 'shipping_information',
            },
        ),
    ]
