# Generated by Django 4.2.5 on 2023-10-25 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('user_onboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslineitems',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='user_onboard.product'),
        ),
        migrations.AddField(
            model_name='saleslineitems',
            name='sales_id',
            field=models.ForeignKey(db_column='sales_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_items', to='sales.sales'),
        ),
        migrations.AddField(
            model_name='salesfooter',
            name='sales_id',
            field=models.ForeignKey(db_column='sales_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sales'),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='sales.customer'),
        ),
        migrations.AddField(
            model_name='sales',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
