# Generated by Django 4.2.5 on 2023-09-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_onboard', '0020_alter_softwarecost_amount_ownerequity'),
        ('sales', '0002_alter_sales_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslineitems',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='user_onboard.product'),
        ),
    ]
