# Generated by Django 4.2.5 on 2023-10-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_saleslineitems_sales_line_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sales_footer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales_line_no',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='shipping_no',
        ),
        migrations.AddField(
            model_name='salesfooter',
            name='sales_id',
            field=models.ForeignKey(db_column='sales_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sales'),
        ),
        migrations.AddField(
            model_name='saleslineitems',
            name='sales_id',
            field=models.ForeignKey(db_column='sales_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sales'),
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='sales_id',
            field=models.ForeignKey(db_column='sales_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.sales'),
        ),
    ]
