# Generated by Django 4.2.5 on 2023-10-03 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_sales_sales_footer_remove_sales_sales_line_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslineitems',
            name='sales_id',
            field=models.ForeignKey(db_column='sales_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_items', to='sales.sales'),
        ),
    ]
