# Generated by Django 4.2.5 on 2023-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_saleslineitems_sales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
    ]
